Repository Team8-Open-Mind/OpenMind, pull requests merged in 2024-01, with the labels that each got.

#28 style : reset.css button
  src/style/reset/reset.js
Labels: 💄 style

#29 ✨feat: 아이콘 스프라이트로 추가
  public/image/icon/sprite_icon_black.svg
  src/components/ui/atoms/sprite-icon/spriteIcon.jsx
  src/components/ui/atoms/user-card/UserCard.jsx
Labels: ✨ feat, 🧹 chore

#35 Feat/스프라이트 아이콘 제작 권지민
  public/image/icon/sprite_icon_black.svg
  public/image/icon/sprite_icon_brown40.svg
  public/image/icon/sprite_icon_gray40.svg
  public/image/icon/sprite_icon_white.svg
  src/components/ui/atoms/Button/Button.jsx
  src/components/ui/atoms/sprite-icon/SpriteIcon.jsx
  src/components/ui/atoms/sprite-icon/spriteIcon.jsx
  src/components/ui/atoms/user-card/UserCard.jsx
Labels: 💄 style, ✨ feat

#39 style/버튼 컴포넌트 반응형 빠진 부분 추가
  src/components/ui/atoms/Button/Button.jsx
  src/components/ui/atoms/Button/media-query.js
Labels: 💄 style, 🧹 chore

#40 Feature/floating sns button 조형민
  jsconfig.path.json
  package-lock.json
  package.json
  public/image/social-media-icon/clipboard-icon.svg
  public/image/social-media-icon/facebook-icon.svg
  public/image/social-media-icon/kakao-icon.svg
  src/App.jsx
  src/components/ui/atoms/Button/floating-button/FloatingButton.jsx
  src/components/ui/atoms/Button/floating-button/floating-delete-button/FloatingDeleteButton.jsx
  src/components/ui/atoms/Button/floating-button/floating-write-question-button/FloatingWriteQuestionButton.jsx
  src/components/ui/atoms/Button/share-button/ShareButton.jsx
  src/components/ui/atoms/Reaction/Reaction.jsx
  src/components/ui/atoms/TestComponent.jsx
  src/components/ui/atoms/user-card/UserCard.jsx
  src/hooks/useResizeObserver.js
  src/hooks/useSNSShare.js
  src/shared/layout/Layout.jsx
  src/style/box-shadow/boxShadow.js
  src/style/breakpoints/media-breakpoints.js
  src/style/breakpoints/mediaBreakpoints.js
  src/utils/style-utils/getNullIfIncludePercent.js
  vite.config.js
Labels: 🐛 fix, ✨ feat, 🧹 chore

#43 refactor/버튼에 onClickHandler 추가
  src/components/ui/atoms/Button/Button.jsx
Labels: ♻️ refactor, 🧹 chore

#42 Feat/async hook 만들었음 권지민
  package-lock.json
  package.json
  src/api/getTotalSubject.js
  src/components/ui/atoms/Button/media-query.js
  src/hooks/useAsync.js
Labels: ✨ feat, 🧹 chore

#44 💄 style: button 컴포넌트 line-height 추가
  src/components/ui/atoms/Button/Button.jsx
  src/components/ui/atoms/Button/media-query.js
Labels: 💄 style, 🧹 chore

#49 🧹 chore: 스프라이트 아이콘 이미지 이름 피그마대로 변경
  public/image/icon/sprite_icon_gray10.svg
  public/image/icon/sprite_icon_gray60.svg
Labels: 🧹 chore

#50 feat: QuestionModal 추가
  src/components/ui/atoms/profile-sample.js
  src/components/ui/atoms/user-card/UserCard.jsx
  src/components/ui/molecules/modal/AddQuestionModal.jsx
  src/components/ui/molecules/modal/Modal.jsx
  src/pages/test-page/TestPage.jsx
  src/shared/routes/routes.jsx
Labels: ✨ feat

#51 Feat/use async 리펙토링 권지민
  src/hooks/useAsync.js
  src/hooks/useAsyncOnMount.js
  src/pages/list-page/ListPage.jsx
Labels: ♻️ refactor

#52 refactor/transient prop 사용하여 button,sprite 리펙토링
  src/components/ui/atoms/Button/Button.jsx
  src/components/ui/atoms/sprite-icon/SpriteIcon.jsx
Labels: ♻️ refactor, 🧹 chore

#55 feat: post페이지 컴포넌트 추가
  public/image/empty-box-image.svg
  src/components/ui/atoms/no-question-box/NoQuestionBox.jsx
  src/components/ui/atoms/toast/Toast.jsx
  src/components/ui/molecules/modal/AddQuestionModal.jsx
Labels: ✨ feat

#56 Feat/cofirm alert hook 권지민
  src/components/ui/molecules/modal/ConfirmAlertModal.jsx
  src/hooks/useConfirmAlert.jsx
  src/pages/answer-page/AnswerPage.jsx
  src/style/reset/reset.js
Labels: ✨ feat

#59 Feat/feed card 수정중 스프라이트 아이콘 추가 권지민
  public/image/icon/sprite_icon_gray50.svg
  src/components/ui/molecules/feed-card/FeedCard.jsx
  src/components/ui/molecules/feed-card/FeedCardContainer.jsx
  src/hooks/useConfirmAlert.jsx
  src/pages/answer-page/AnswerPage.jsx
Labels: ♻️ refactor, 🧹 chore

#62 Feat/feed card 수정중 권지민
  src/components/ui/atoms/Badge/Badge.jsx
  src/components/ui/atoms/Button/edit-button/EditButton.jsx
  src/components/ui/atoms/question-box/AnswerBox.jsx
  src/components/ui/molecules/feed-card/FeedCard.jsx
  src/components/ui/molecules/feed-card/FeedCardContainer.jsx
Labels: ✨ feat, 🧹 chore

#67 🧹 chore: useCloseModal, useModalComponent 훅 사용 예시
  src/api/answers/안에파일없으면폴더깃헙안올라가서만듦.js
  src/api/getTotalSubject.js
  src/api/subjects/안에파일없으면폴더깃헙안올라가서만듦.js
  src/components/ui/atoms/toast/Toast.jsx
  src/components/ui/molecules/card/link-card/Bookmark.jsx
  src/components/ui/molecules/card/link-card/Bookmark.module.css
  src/components/ui/molecules/card/link-card/CardCover.jsx
  src/components/ui/molecules/card/link-card/CardImage.jsx
  src/components/ui/molecules/card/link-card/CreatedAt.jsx
  src/components/ui/molecules/card/link-card/Description.jsx
  src/components/ui/molecules/card/link-card/KebabButton.jsx
  src/components/ui/molecules/card/link-card/TimeElapsed.jsx
  src/components/ui/molecules/card/link-card/context/CardProvider.jsx
  src/components/ui/molecules/card/link-card/index.js
  src/pages/test-page/TestPage.jsx
Labels: ♻️ refactor, 🧹 chore

#69 feat: 유저데이터 불러오는 api작성
  src/api/getQuestionData.js
  src/api/getUserData.js
  src/components/ui/molecules/feed-card/FeedCard.jsx
  src/components/ui/molecules/feed-card/FeedCardContainer.jsx
  src/hooks/useSetUser.js
  src/pages/question-feed-page/QuestFeedPage.jsx
  src/pages/test-page/TestPage.jsx
Labels: ✨ feat

#66 Feat/feed card 기능추가중 권지민
  src/api/answer/getAnswerLists.js
  src/assets/thumbs-up.svg
  src/components/ui/atoms/Badge/Badge.jsx
  src/components/ui/atoms/Reaction/Reaction.jsx
  src/components/ui/atoms/ReplyTypeSwitch.jsx/ReplyTypeSwitch.jsx
  src/components/ui/atoms/edit-type-box/EditTypeBox.jsx
  src/components/ui/atoms/input/input-text-area/InputTextArea.jsx
  src/components/ui/atoms/question-box/AnswerBox.jsx
  src/components/ui/atoms/question-box/QuestionBox.jsx
  src/components/ui/atoms/question-box/ReadTypeBox.jsx
  src/components/ui/atoms/reject-reply/RejectReplyButton.jsx
  src/components/ui/atoms/reply-type-box/ReplyTypeBox.jsx
  src/components/ui/molecules/feed-card/FeedCard.jsx
  src/components/ui/molecules/feed-card/FeedCardContainer.jsx
  src/pages/answer-page/AnswerPage.jsx
  src/utils/card-type/feedCardType.js
  src/utils/time/timeStamp.js
Labels: ✨ feat, ♻️ refactor

#70 🧹 chore: useSNSShare javascript key 맞춰서 변경
  src/hooks/useSNSShare.js
Labels: 🧹 chore

#71 ✨ feat: FloatingButton boxShadow 추가 여부 선택할 수 있도록 변경
  src/components/ui/atoms/Button/floating-button/FloatingButton.jsx
Labels: ✨ feat

#72 Feat/feedcard 진행 , 위로가기버튼 custom hook, 카드 삭제 버튼 디자인 추가
  src/components/ui/atoms/Badge/Badge.jsx
  src/components/ui/atoms/Badge/BadgeBox.jsx
  src/components/ui/atoms/ReplyTypeSwitch.jsx/ReplyTypeSwitch.jsx
  src/components/ui/atoms/question-box/AnswerBox.jsx
  src/components/ui/atoms/rejected-type-box/RejectedTypeBox.jsx
  src/components/ui/atoms/scroll-top/ScrollTopButton.jsx
  src/components/ui/atoms/scroll-top/media-query.js
  src/components/ui/molecules/feed-card/FeedCard.jsx
  src/components/ui/molecules/feed-card/FeedCardContainer.jsx
  src/hooks/useConfirmAlert.jsx
  src/hooks/useScrollToTop.js
  src/pages/answer-page/AnswerPage.jsx
  src/style/reset/reset.js
  src/style/theme/theme.js
Labels: ✨ feat, ♻️ refactor

#73 💄 style: feed background 높이 수정
  src/pages/answer-page/AnswerPage.jsx
Labels: 💄 style

#75 ♻️ refactor: NoList 컴포넌트 children 으로 텍스트 넘겨줄 수 있도록 수정
  src/pages/answer-page/AnswerPage.jsx
  src/pages/list-page/comp/list-contents/ListContents.jsx
  src/pages/list-page/comp/list-contents/comp/no-lists/NoLists.jsx
Labels: ♻️ refactor

#74 feat: 메인페이지 구현
  src/components/ui/molecules/feed-card/FeedCardContainer.jsx
  src/hooks/useSetUser.js
  src/pages/main-page/MainPage.jsx
  src/pages/question-feed-page/QuestFeedPage.jsx
  src/pages/test-page/TestPage.jsx
Labels: ✨ feat

#79 ✨ feat: NoLists 버튼기능 빠뜨린 거 추가
  src/pages/list-page/comp/list-contents/ListContents.jsx
Labels: ✨ feat, 🧹 chore

#81 🧹 chore: 좌우(<, >) 아이콘 감싸는 버튼을 호버 했을 때 아이콘 색 변경되도록 수정
  src/pages/list-page/comp/list-contents/comp/page-turner/PageTurnner.jsx
Labels: 🧹 chore

#82 🧹 chore: 좌우(<, >) 아이콘 감싸는 버튼을 호버 했을 때 아이콘 색 변경되도록 수정
  src/pages/list-page/comp/list-contents/comp/page-turner/PageTurnner.jsx
Labels: 🧹 chore

#80 Feat/피드 api 연결 권지민
  src/api/answers/getAnswerLists.js
  src/api/answers/postAnswer.js
  src/api/answers/안에파일없으면폴더깃헙안올라가서만듦.js
  src/api/questions/deleteQuestion.js
  src/components/ui/atoms/Badge/BadgeBox.jsx
  src/components/ui/atoms/ReplyTypeSwitch.jsx/ReplyTypeSwitch.jsx
  src/components/ui/atoms/question-box/AnswerBox.jsx
  src/components/ui/atoms/reply-type-box/ReplyTypeBox.jsx
  src/components/ui/molecules/feed-card/FeedCard.jsx
  src/components/ui/molecules/feed-card/FeedCardContainer.jsx
  src/pages/answer-page/AnswerPage.jsx
Labels: ✨ feat

#83 ♻️ refactor: usePaginate 리팩토링, GridItem 긴 이름 튀어나가는 거 막음.
  src/components/ui/molecules/grid/GridItem.jsx
  src/hooks/usePaginate.js
  src/hooks/useResizeObserver.js
  src/pages/list-page/comp/list-contents/ListContents.jsx
  src/pages/list-page/comp/list-contents/comp/page-turner/PageTurnner.jsx
Labels: ♻️ refactor, 🧹 chore

#84 Feat/ 답변 보내기 post는 되지만 리렌더링 안되는 부분 수정 -권지민
  src/api/answers/postAnswer.js
  src/components/ui/atoms/Badge/BadgeBox.jsx
  src/components/ui/atoms/ReplyTypeSwitch.jsx/ReplyTypeSwitch.jsx
  src/components/ui/atoms/question-box/AnswerBox.jsx
  src/components/ui/atoms/reply-type-box/ReplyTypeBox.jsx
  src/components/ui/molecules/feed-card/FeedCard.jsx
  src/components/ui/molecules/feed-card/FeedCardContainer.jsx
  src/hooks/useAsync.js
  src/hooks/useAsyncOnMount.js
  src/pages/answer-page/AnswerPage.jsx
  src/pages/main-page/MainPage.jsx
Labels: ✨ feat, ♻️ refactor

#85 ✨ feat: 파워 드릴링으로 리액션 기능 추가
  src/api/questions/postReaction.js
  src/components/ui/atoms/Reaction/Reaction.jsx
  src/components/ui/atoms/question-box/AnswerBox.jsx
  src/components/ui/molecules/feed-card/FeedCard.jsx
Labels: ✨ feat

#88 🧹 chore: useAsyncOnMount 디스트럭쳐링 맞춰서 코드 변경
  src/pages/list-page/comp/list-contents/ListContents.jsx
Labels: 🧹 chore

#89 Feat/거절, 수정 기능 추가 -권지민
  src/api/answers/patchAnswer.js
  src/api/answers/postAnswer.js
  src/components/ui/atoms/ReplyTypeSwitch.jsx/ReplyTypeSwitch.jsx
  src/components/ui/atoms/edit-type-box/EditTypeBox.jsx
  src/components/ui/atoms/question-box/AnswerBox.jsx
  src/components/ui/atoms/reject-reply/RejectReplyButton.jsx
  src/components/ui/atoms/reply-type-box/ReplyTypeBox.jsx
  src/components/ui/molecules/feed-card/FeedCard.jsx
  src/hooks/useConfirmAlert.jsx
  src/pages/answer-page/AnswerPage.jsx
  src/utils/card-type/feedCardType.js
Labels: ✨ feat

#90 🐛 fix: AnswerPage, QuestionFeedPage 리렌더링 되도록 수정
  .eslintrc.cjs
  src/api/answers/getAnswerLists.js
  src/api/getUserData.js
  src/api/subjects/getUserData.js
  src/components/ui/atoms/question-box/AnswerBox.jsx
  src/hooks/useSetUser.js
  src/pages/answer-page/AnswerPage.jsx
  src/pages/question-feed-page/QuestFeedPage.jsx
  src/utils/time/timeStamp.js
Labels: 🐛 fix, ♻️ refactor

#92 Feat/거절기능 수정/답변 상태에 맞게 api 요청 보내도록 수정 권지민
  src/components/ui/atoms/ReplyTypeSwitch.jsx/ReplyTypeSwitch.jsx
  src/components/ui/atoms/edit-type-box/EditTypeBox.jsx
  src/components/ui/atoms/reject-reply/RejectReplyButton.jsx
  src/components/ui/atoms/reply-type-box/ReplyTypeBox.jsx
Labels: 🐛 fix

#93 🐛 fix: parameter를 받도록 고침
  src/api/getQuestionData.js
  src/pages/main-page/MainPage.jsx
  src/pages/main-page/hooks/useNavigateAnswer.js
  src/pages/question-feed-page/QuestFeedPage.jsx
Labels: 🐛 fix

#96 💄 style: 피드카드 ui 깨지는 부분 급 수정
  src/components/ui/atoms/question-box/AnswerBox.jsx
Labels: 💄 style

#99 🧹 chore/navBar 링크 잘못된 것 수정
  src/components/ui/molecules/nav-bar/NavBar.jsx
Labels: 🧹 chore

#101 refactor:/피드 카드 ui 별로 수정 추가
  src/components/ui/atoms/question-box/AnswerBox.jsx
Labels: ♻️ refactor

#102 refactor/useParam으로 id url값 받아오기
  src/hooks/useCheckAuth.js
Labels: ♻️ refactor

#103 refactor/navBar 메뉴 localStrage id 잇을때만 보이도록 변경
  src/components/ui/molecules/nav-bar/NavBar.jsx
  src/hooks/useCheckAuth.js
Labels: ♻️ refactor

#107 chore/폴더명 수정했음
  src/api/subjects/getUserData.js
  src/components/ui/atoms/edit-type-box/EditTypeBox.jsx
  src/components/ui/atoms/question-box/AnswerBox.jsx
  src/components/ui/atoms/reaction/Reaction.jsx
  src/components/ui/atoms/reply-type-box/ReplyTypeBox.jsx
  src/components/ui/atoms/reply-type-switch/ReplyTypeSwitch.jsx
  src/components/ui/molecules/feed-card/FeedCard.jsx
  src/components/ui/molecules/feed-card/FeedCardContainer.jsx
  src/components/ui/molecules/modal/AddQuestionModal.jsx
  src/hooks/useSNSShare.js
  src/pages/answer-page/AnswerPage.jsx
  src/pages/list-page/ListPage.jsx
  src/pages/main-page/MainPage.jsx
  src/pages/question-feed-page/QuestFeedPage.jsx
Labels: 🧹 chore

#112 chore/reaction 수정
  src/pages/question-feed-page/QuestFeedPage.jsx
Labels: 🧹 chore

#113 chore/수정했던게 빠져있어서 다시 추가
  src/components/ui/molecules/nav-bar/NavBar.jsx
  src/hooks/useCheckAnswerPath.js
Labels: 🧹 chore

#116 ✨ feat: netlify.toml 파일 redirect를 위해 추가
  netlify.toml
Labels: 🐛 fix, 🧹 chore

#117 🧹 chore: eslint underscore(_) 붙이면 unused-var 에러 끄도록 설정
  .eslintrc.cjs
Labels: 🧹 chore

#119 refactor/ 논의때 나온 수정 사항 반영 권지민
  src/components/ui/atoms/edit-type-box/EditTypeBox.jsx
  src/components/ui/atoms/reply-type-box/ReplyTypeBox.jsx
  src/hooks/useCheckAuth.js
  src/pages/answer-page/AnswerPage.jsx
  src/pages/list-page/ListPage.jsx
  src/pages/main-page/MainPage.jsx
  src/pages/question-feed-page/QuestFeedPage.jsx
Labels: ♻️ refactor, 🧹 chore

#120 fix: 토스트가 안나타나는 버그 수정
  src/pages/question-feed-page/QuestFeedPage.jsx
Labels: 🐛 fix

#123 Feat/refactoring 권지민
  src/components/ui/molecules/feed-card/FeedCardContainer.jsx
  src/hooks/useCloseModal.js
  src/pages/main-page/MainPage.jsx
Labels: ♻️ refactor

#124 Feat/refactoring 권지민
  src/components/ui/atoms/badge/BadgeBox.jsx
  src/components/ui/atoms/toast/Toast.jsx
  src/components/ui/molecules/feed-card/FeedCardContainer.jsx
  src/pages/answer-page/AnswerPage.jsx
  src/pages/main-page/MainPage.jsx
Labels: ♻️ refactor

#125 Feature/drop down refactor 조형민
  src/components/ui/atoms/dropdown/DropdownOption.jsx
  src/components/ui/atoms/dropdown/arrow-dropdown/ArrowDropdown.jsx
  src/components/ui/atoms/dropdown/context/DropdownProvider.jsx
  src/components/ui/atoms/dropdown/hamburger-dropdown/HamburgerDropdown.jsx
  src/hooks/useAsyncFn_V2.js
Labels: ✨ feat, ♻️ refactor

#127 ♻️ refactor: useAsync_V2 enabled 옵션 추가
  src/hooks/useAsync_V2.js
  src/pages/answer-page/AnswerPage.jsx
  src/pages/question-feed-page/QuestFeedPage.jsx
Labels: ✨ feat, ♻️ refactor

#126 fix: 이미지 및 토스트 수정
  index.html
  public/image/mainimage-for-meta.png
  src/components/ui/atoms/no-question-box/NoQuestionBox.jsx
  src/components/ui/molecules/nav-bar/NavBar.jsx
  src/pages/answer-page/AnswerPage.jsx
  src/pages/question-feed-page/QuestFeedPage.jsx
Labels: 🐛 fix, ✨ feat, 🧹 chore

#128 Feat/answer페이지 modal, padding값 수정
  src/pages/answer-page/AnswerPage.jsx
Labels: 💄 style, 🐛 fix

#130 Update README.md
  README.md
Labels: 🧹 chore

#129 🐛 fix: 드롭다운 임시 방편으로 initialSelectedValue를 직접 프롭으로 받도록 함.
  src/components/ui/atoms/dropdown/DropdownOption.jsx
  src/components/ui/atoms/dropdown/context/DropdownProvider.jsx
Labels: 🐛 fix

#131 ♻️ refactor: 드롭다운 리팩토링
  src/components/ui/atoms/dropdown/DropdownMenu.jsx
  src/components/ui/atoms/dropdown/DropdownOption.jsx
  src/components/ui/atoms/dropdown/DropdownSelect.jsx
  src/components/ui/atoms/dropdown/arrow-dropdown/ArrowDropdown.jsx
  src/components/ui/atoms/dropdown/context/DropdownProvider.jsx
  src/components/ui/atoms/dropdown/hamburger-dropdown/HamburgerDropdown.jsx
  src/pages/answer-page/AnswerPage.jsx
  src/pages/question-feed-page/QuestFeedPage.jsx
Labels: ♻️ refactor

#132 refactor/알럿 여러개 찍혀있는거 코드 수정
  src/components/ui/atoms/badge/BadgeBox.jsx
  src/components/ui/molecules/feed-card/FeedCard.jsx
  src/components/ui/molecules/feed-card/FeedCardContainer.jsx
  src/pages/answer-page/AnswerPage.jsx
Labels: ♻️ refactor

#133 리드미 수정 진행중
  README.md
Labels: 📝 docs

#134 기술스택,협업툴,배포툴 로고 업데이트
  README.md
Labels: 📝 docs

#135 read me 시연 gif 추가
  README.md
Labels: 📝 docs

#136 readme 공백 제거
  README.md
Labels: 📝 docs

#137 readme 위키 링크도 추가
  README.md
Labels: 📝 docs

#138 Update README.md
  README.md
Labels: 📝 docs
